modLoader="javafml"
loaderVersion="[34,)"
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]]
modId="clockhud"
version="2.2.0"
displayName="Clock HUD"
#logoFile="examplemod.png"
credits="Created by QKninja"
authors="QKninja"
description='''
    A simple clock GUI to check the time.
'''

[[dependencies.clockhud]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.clockhud]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
