modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="clockhud"
version="2.1.0"
displayName="Clock HUD"
#logoFile="examplemod.png"
credits="Created by QKninja"
authors="QKninja"
description='''
    A simple clock GUI to check the time.
'''

[[dependencies.clockhud]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.clockhud]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
